<?php

namespace AppBundle\Entity;

/**
 * BarHasBeersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarHasBeersRepository extends \Doctrine\ORM\EntityRepository
{
}
