<?php

namespace AppBundle\Entity;

/**
 * BarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarRepository extends \Doctrine\ORM\EntityRepository
{
}
